### ISSUE TITLE
botが読み上げ時にffmpeg/avconv not found!とエラーを吐き出し読み上げない

### ISSUE THREAD

**Issue by mid0w0dim** [yukki2288/yomiage-chan#14]
初歩的な質問ですみません。
botが読み上げ時に

Error: FFmpeg/avconv not found!

    at FFmpeg.getInfo (/app/node_modules/prism-media/src/core/FFmpeg.js:143:11)

    at FFmpeg.create (/app/node_modules/prism-media/src/core/FFmpeg.js:156:38)

    at new FFmpeg (/app/node_modules/prism-media/src/core/FFmpeg.js:45:27)

    at Object.transformer (/app/node_modules/@discordjs/voice/dist/index.js:8:13814)

    at /app/node_modules/@discordjs/voice/dist/index.js:8:16735

    at Array.map (<anonymous>)

    at Object.We (/app/node_modules/@discordjs/voice/dist/index.js:8:16726)

    at /app/src/connectionManager.js:243:32

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

とエラーを吐き出し読み上げない状態です

https://goody-jp.com/static%E3%81%AAffmpeg%E3%81%8C%E3%81%A8%E3%81%A6%E3%82%82useful%E3%81%A0%E3%81%A3%E3%81%9F%E8%A9%B1/
このサイトを参考しコテンナ内のbot_app_1のCLIから
wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz
tar Jxvf ./ffmpeg-release-arm64-static.tar.xz
cp ./ffmpeg-5.0.1-arm64-static/ffmpeg /usr/local/bin/

と打ち、再起動を行ってみましたが。変わりませんでした。

**Comment by yukki2288** [comment]
こんにちは。
ご覧いただきありがとうございます。

こちらのエラーですが、私がpackage.jsonからffmpeg-staticを削除してしまったことによるものだと判明しました。
お手を煩わせてしまい、申し訳ないです。

先ほどpackage.jsonを更新したので、`git pull origin main`をしてからコンテナを再起動していただけますと幸いです。
よろしくお願いします。

**Comment by mid0w0dim** [comment]
お返事ありがとうございます。
無事上記のエラーが出なくなりました。
ですが、文字を打っても喋らなく
ログの方を見たら

Error: Cannot play audio as no valid encryption package is installed.

- Install sodium, libsodium-wrappers, or tweetnacl.

- Use the generateDependencyReport() function for more information.


    at Object.K (/app/node_modules/@discordjs/voice/dist/index.js:1:8811)

    at z.encryptOpusPacket (/app/node_modules/@discordjs/voice/dist/index.js:6:3513)

    at z.createAudioPacket (/app/node_modules/@discordjs/voice/dist/index.js:6:3314)

    at z.prepareAudioPacket (/app/node_modules/@discordjs/voice/dist/index.js:6:2445)

    at G.prepareAudioPacket (/app/node_modules/@discordjs/voice/dist/index.js:8:10268)

    at /app/node_modules/@discordjs/voice/dist/index.js:8:2718

    at Array.forEach (<anonymous>)

    at B._preparePacket (/app/node_modules/@discordjs/voice/dist/index.js:8:2705)

    at B._stepPrepare (/app/node_modules/@discordjs/voice/dist/index.js:8:2420)

    at ue (/app/node_modules/@discordjs/voice/dist/index.js:1:4412)


とエラーが出ていました

**Comment by yukki2288** [comment]
こんにちは。
二つ目のエラーですが、`@discord.js/voice`に必要なライブラリが不足していることが原因だと思います。
package.jsonのdependenciesの中に、`sodium`は含まれているでしょうか？

もし含まれていない場合は、コンテナ内で`npm i sodium@3.0.2`を実行して、再起動してみてください。

もし含まれている場合は、下記のライブラリからどれか一つインストールして試してみてください。
```
npm i sodium-native@3.3.0
npm i tweetnacl@1.0.3
npm i libsodium-wrappers@0.7.9
```
（参考）[@discord.js/voice Document](https://discord.js.org/#/docs/voice/main/general/welcome) > Welcom > Dependencies > Encryption Libraries

お手数ですがお試しいただけますと幸いです。

**Comment by mid0w0dim** [comment]
こんにちわ。
返信ありがとうございます。

上記の方法で無事、botが喋るようになりました。
ありがとうございました。

**Comment by yukki2288** [comment]
こんにちは。
無事に解決したようでなによりです。
ご報告いただき、ありがとうございました。
